# Generated by Django 4.1 on 2026-02-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_app', '0003_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='kyc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
